title: Page Title
email: mei@otoha.moe
description: >- # this means to ignore newlines until "baseurl:"
  A paragraph describing your webpage.
baseurl: "/" # the subpath of your site
url: "otoha.moe" # the base hostname & protocol for your site
twitter_username: alex_lyu
github_username:  maplelolita

# Required plugins for the theme to work properly
plugins:
  - jekyll-remote-theme
  - jemoji

# Including jekyll-shell-theme using the jekyll-remote-theme plugin
remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed

highlighter: rouge #selecting the highlighter, default is rouge

header_pages:
  - index.md

# controls how big the shell and font looks
font-size: small # options: [small] or [large]
